DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS images CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS admins CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;
DROP TABLE IF EXISTS messages CASCADE;


CREATE TABLE admins
(
    id       UUID PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(50)  NOT NULL CHECK (role IN ('ROLE_USER', 'ROLE_ADMIN'))
);

CREATE TABLE products
(
    product_id    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(100) NOT NULL,
    category      VARCHAR(50)  NOT NULL,
    description   TEXT,
    price         INTEGER      NOT NULL,
    shipping_cost INTEGER      NOT NULL,
    brand         VARCHAR(50),
    stock_status  VARCHAR(50)  NOT NULL,
    shipping_time INTEGER,
    active        BOOLEAN      NOT NULL DEFAULT TRUE
);

CREATE TABLE images
(
    image_id   UUID PRIMARY KEY,
    url        TEXT NOT NULL,
    product_id BIGINT REFERENCES products (product_id) ON DELETE CASCADE
);

CREATE TABLE users
(
    id         UUID PRIMARY KEY,
    email      VARCHAR(100) NOT NULL UNIQUE,
    firstname  VARCHAR(50),
    lastname   VARCHAR(50),
    password   VARCHAR(255) NOT NULL,
    role       VARCHAR(50)  NOT NULL,
    phone      VARCHAR(50),
    postcode   VARCHAR(20),
    address    VARCHAR(255),
    active     BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP             DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE orders
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number      VARCHAR(50) UNIQUE,
    user_id           UUID           REFERENCES users (id) ON DELETE SET NULL,
    total_order_price NUMERIC(12, 2) NOT NULL,
    ordered_date      DATE,
    delivery_date     DATE,
    order_status      VARCHAR(50)    NOT NULL,
    shipping_address  VARCHAR(255)   NOT NULL,
    payment_method    VARCHAR(50),
    delivery_postcode INTEGER
);

CREATE TABLE order_items
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT  NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id BIGINT  NOT NULL REFERENCES products (product_id) ON DELETE CASCADE,
    quantity   INTEGER NOT NULL CHECK (quantity > 0),
    price      NUMERIC(12, 2)
);

CREATE TABLE messages
(
    message_id UUID PRIMARY KEY,
    user_id           UUID           REFERENCES users (id) ON DELETE SET NULL,
    name       VARCHAR(100),
    email      VARCHAR(255),
    subject    VARCHAR(255),
    message    TEXT,
    created_at TIMESTAMP,
    admin_reply TEXT,
    replied_at TIMESTAMP,
    status varchar(50) NOT NULL,
    read_at TIMESTAMP
);

CREATE TABLE reviews
(
    review_id  VARCHAR(100) PRIMARY KEY,
    product_id BIGINT  NOT NULL REFERENCES products (product_id) ON DELETE CASCADE,
    user_id    UUID    REFERENCES users (id) ON DELETE SET NULL,
    rating     INTEGER NOT NULL,
    comment    TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO products (name, category, description, price, shipping_cost, brand, stock_status, shipping_time, active)
VALUES
-- =========================
-- PIANOS (1-7)
-- =========================
('PrestoTune White Upright F', 'PIANOS',
 'Elegant white upright piano with smooth key action and clear, balanced tone for home and studio.', 350000, 0,
 'PrestoTune Pianos', 'IN_STOCK', 5, TRUE),

('SonataCraft Ivory Grand LX', 'PIANOS',
 'Premium white grand piano with rich sustain and refined voicing, designed for living room and stage.', 1200000, 9000,
 'SonataCraft Pianos', 'IN_STOCK', 7, TRUE),

('SonataCraft Ruby Grand', 'PIANOS',
 'Striking red grand piano with concert-style projection and precise, responsive action.', 5559900, 0,
 'SonataCraft Pianos', 'IN_STOCK', 7, TRUE),

('Melodique Black Upright p44', 'PIANOS',
 'Classic black upright piano with warm bass response, stable tuning feel, and smooth playability.', 300000, 0,
 'Melodique Keys', 'IN_STOCK', 5, TRUE),

('Melodique Walnut Upright', 'PIANOS',
 'Warm walnut-finish upright piano with mellow character, ideal for practice and lessons.', 279900, 0,
 'Melodique Keys', 'IN_STOCK', 5, TRUE),

('EchoLynx Compact White', 'PIANOS',
 'Compact white digital piano with clean design, dual speakers, and responsive weighted feel.', 39900, 2500,
 'EchoLynx Keys', 'IN_STOCK', 3, TRUE),

('Newerton Studio Black Pro', 'PIANOS',
 'Studio-focused black piano with weighted feel and expressive dynamics for recording and rehearsals.', 99900, 0,
 'Newerton Keys', 'OUT_OF_STOCK', 4, TRUE),

-- =========================
-- GUITARS (8-14)
-- =========================
('StrumVista Midnight Black', 'GUITARS',
 'Modern electric guitar with tight low-end, comfortable neck, and versatile tones for rock and pop.', 129900, 1900,
 'StrumVista Guitars', 'IN_STOCK', 4, TRUE),

('FretHarmony Cherry Classic', 'GUITARS',
 'Classic double-cut electric guitar with punchy mids, smooth lead feel, and reliable tuning stability.', 89900, 1500,
 'FretHarmony Instruments', 'IN_STOCK', 3, TRUE),

('SoundForge Polar White X', 'GUITARS',
 'Sharp-looking white electric guitar built for fast playability and crisp, articulate attack.', 97500, 1800,
 'SoundForge', 'IN_STOCK', 3, TRUE),

('EchoTone Sunburst Vintage V', 'GUITARS',
 'Vintage-inspired sunburst electric guitar with warm mids, singing sustain, and classic styling.', 149900, 2500,
 'EchoTone Guitars', 'OUT_OF_STOCK', 6, TRUE),

('ToneRiver Amber Flame', 'GUITARS',
 'Single-cut electric guitar with warm sustain, clear note separation, and stage-ready hardware.', 159900, 2500,
 'ToneRiver', 'IN_STOCK', 5, TRUE),

('Newerton Honeyburst Pro', 'GUITARS',
 'Premium electric guitar with rich harmonics, stable trem option, and comfortable modern profile.', 169900, 2500,
 'Newerton Strings', 'IN_STOCK', 6, TRUE),

('ClassicKeys Crimson Standard', 'GUITARS',
 'Solid-body electric guitar with tight response, great intonation, and bold modern look.', 119900, 2000,
 'ClassicKeys Co.', 'IN_STOCK', 5, TRUE),

-- =========================
-- VIOLINS (15-20)
-- =========================
('AriaVale Student 4/4', 'VIOLINS',
 'Student-friendly 4/4 violin with clear tone, stable setup, and comfortable playability.', 19900, 1200,
 'AriaVale Violins', 'IN_STOCK', 3, TRUE),

('CrescendoCraft Student 3/4', 'VIOLINS',
 '3/4 violin for younger players with warm tone and reliable tuning stability.', 15900, 1000,
 'CrescendoCraft', 'IN_STOCK', 3, TRUE),

('SonataBow Travel Outfit', 'VIOLINS',
 'Durable violin outfit with robust case, designed for lessons, travel, and daily practice.', 29900, 1800,
 'SonataBow', 'IN_STOCK', 4, TRUE),

('LuthierWorks Concert 4/4', 'VIOLINS',
 'Concert-grade 4/4 violin with strong projection, nuanced response, and premium craftsmanship.', 249900, 3500,
 'LuthierWorks', 'IN_STOCK', 7, TRUE),

('PrestoStrings Vintage V1', 'VIOLINS',
 'Vintage-voiced violin with sweet highs, warm lows, and excellent bow articulation.', 79900, 2200,
 'PrestoStrings', 'OUT_OF_STOCK', 6, TRUE),

('OrchestraLine Pro Setup', 'VIOLINS',
 'Professional setup focused on stability, projection, and refined dynamic control.', 129900, 2800,
 'OrchestraLine', 'IN_STOCK', 6, TRUE);


INSERT INTO images (image_id, url, product_id)
VALUES
-- =========================
-- PIANOS (1-7)
-- White Upright -> white upright image
('00000000-0000-0000-0000-000000000001', '/pianos/p-17.jpg', 1),
('00000000-0000-0000-0000-000000000002', '/pianos/p-19.jpg', 1),

-- White Grand -> white grand images
('00000000-0000-0000-0000-000000000003', '/pianos/p-14.jpg', 2),
('00000000-0000-0000-0000-000000000004', '/pianos/p-16.jpg', 2),

-- Red Grand -> red grand image (p-18 looks red-accent), plus another grand
('00000000-0000-0000-0000-000000000005', '/pianos/p-18.jpg', 3),
('00000000-0000-0000-0000-000000000006', '/pianos/p-3.jpg', 3),

-- Black Upright -> black upright images
('00000000-0000-0000-0000-000000000007', '/pianos/p-6.jpg', 4),
('00000000-0000-0000-0000-000000000008', '/pianos/p-12.jpg', 4),

-- Walnut Upright -> wood upright images
('00000000-0000-0000-0000-000000000009', '/pianos/p-10.jpg', 5),
('00000000-0000-0000-0000-000000000010', '/pianos/p-11.jpg', 5),

-- Compact White -> white compact / white finish
('00000000-0000-0000-0000-000000000011', '/pianos/p-13.jpg', 6),
('00000000-0000-0000-0000-000000000012', '/pianos/p-17.jpg', 6),

-- Studio Black -> sleek black upright images
('00000000-0000-0000-0000-000000000013', '/pianos/p-7.jpg', 7),
('00000000-0000-0000-0000-000000000014', '/pianos/p-15.jpg', 7),

-- =========================
-- GUITARS (8-14)
-- Black guitar
('00000000-0000-0000-0000-000000000015', '/guitars/g-1.jpg', 8),
('00000000-0000-0000-0000-000000000016', '/guitars/g-4.jpg', 8),

-- Cherry / red-ish
('00000000-0000-0000-0000-000000000017', '/guitars/g-2.jpg', 9),
('00000000-0000-0000-0000-000000000018', '/guitars/g-8.jpg', 9),

-- White guitar
('00000000-0000-0000-0000-000000000019', '/guitars/g-3.jpg', 10),
('00000000-0000-0000-0000-000000000020', '/guitars/g-10.jpg', 10),

-- Sunburst
('00000000-0000-0000-0000-000000000021', '/guitars/g-5.jpg', 11),
('00000000-0000-0000-0000-000000000022', '/guitars/g-11.jpg', 11),

-- Amber / flame top
('00000000-0000-0000-0000-000000000023', '/guitars/g-6.jpg', 12),
('00000000-0000-0000-0000-000000000024', '/guitars/g-5.jpg', 12),

-- Honeyburst / warm
('00000000-0000-0000-0000-000000000025', '/guitars/g-6.jpg', 13),
('00000000-0000-0000-0000-000000000026', '/guitars/g-12.jpg', 13),

-- Crimson
('00000000-0000-0000-0000-000000000027', '/guitars/g-12.jpg', 14),
('00000000-0000-0000-0000-000000000028', '/guitars/g-2.jpg', 14),

-- =========================
-- VIOLINS (15-20)
-- Student 4/4
('00000000-0000-0000-0000-000000000029', '/violins/v-1.jpg', 15),
('00000000-0000-0000-0000-000000000030', '/violins/v-2.jpg', 15),

-- Student 3/4
('00000000-0000-0000-0000-000000000031', '/violins/v-7.jpg', 16),
('00000000-0000-0000-0000-000000000032', '/violins/v-8.jpg', 16),

-- Travel outfit (case-y look ist nicht sichtbar, aber diverse Bilder ok)
('00000000-0000-0000-0000-000000000033', '/violins/v-9.jpg', 17),
('00000000-0000-0000-0000-000000000034', '/violins/v-10.jpg', 17),

-- Concert grade
('00000000-0000-0000-0000-000000000035', '/violins/v-3.jpg', 18),
('00000000-0000-0000-0000-000000000036', '/violins/v-5.jpg', 18),

-- Vintage voiced
('00000000-0000-0000-0000-000000000037', '/violins/v-6.jpg', 19),
('00000000-0000-0000-0000-000000000038', '/violins/v-5.jpg', 19),

-- Pro setup
('00000000-0000-0000-0000-000000000039', '/violins/v-4.jpg', 20),
('00000000-0000-0000-0000-000000000040', '/violins/v-6.jpg', 20);



INSERT INTO users (id, email, password, phone, address, postcode, firstname, lastname, role, active, created_at)
VALUES ('bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 'maria82@example.com', 'passM@123', 123456789,
        '123 Elm Street, Springfield', '88097', 'Maria', 'Lopez', 'ROLE_USER', TRUE, '2025-05-20 14:12:35'),
       ('22222222-2222-2222-2222-222222222222', 'jack.r@example.com', 'jackR_!Pass4', 123456789,
        '456 Oak Avenue, Centerville', '88097', 'Jack', 'Roberts', 'ROLE_USER', TRUE, '2025-05-15 09:33:21'),
       ('33333333-3333-3333-3333-333333333333', 'li.chen@example.com', 'L1Chen*Pwd', 123456789,
        '789 Maple Lane, Rivertown', '88097', 'Li', 'Chen', 'ROLE_USER', TRUE, '2025-05-10 17:22:40'),
       ('44444444-4444-4444-4444-444444444444', 'sophie.c@example.com', 'Soph!eC2025', 123456789,
        '321 Birch Rd, Hilltown', '88097', 'Sophie', 'Campbell', 'ROLE_USER', TRUE, '2025-05-21 12:05:55'),
       ('55555555-5555-5555-5555-555555555555', 'daniel.k@example.com', 'DanK#pass1', 123456789,
        '654 Cedar Street, Lakeside', '88097', 'Daniel', 'Klein', 'ROLE_USER', TRUE, '2025-05-12 08:11:11'),
       ('66666666-6666-6666-6666-666666666666', 'nina.v@example.com', 'NinaV_22!', 123456789,
        '213 Spruce Blvd, Newfield', '88097', 'Nina', 'Vargas', 'ROLE_USER', TRUE, '2025-05-19 19:30:00'),
       ('77777777-7777-7777-7777-777777777777', 'omar.t@example.com', 'OmarT@pw2025', 123456789,
        '987 Aspen Way, Brookville', '88097', 'Omar', 'Tariq', 'ROLE_USER', TRUE, '2025-05-18 07:45:23'),
       ('88888888-8888-8888-8888-888888888888', 'emily.b@example.com', 'EmB_pass!', 123456789,
        '147 Redwood Dr, Milltown', '88097', 'Emily', 'Bennett', 'ROLE_USER', FALSE, '2025-05-22 10:10:10'),
       ('99999999-9999-9999-9999-999999999999', 'admin.jane@example.com', 'Adm1nJane$', 123456789,
        '852 Pine St, Cityville', '88097', 'Jane', 'Miller', 'ROLE_ADMIN', TRUE, '2025-05-14 15:00:00'),

       ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'user@mail.com',
        '$2a$10$Xu93DE.ETSXbEGMOJeAT6eUASMcOg9YTzVQ8Rleg2EiwTaP5hHR0.', '0432938573', '963 Willow Way, Capitol City',
        '88097', 'Peo', 'Oneal', 'ROLE_USER', TRUE, '2025-05-16 13:13:13'),
       ('11111111-1111-1111-1111-111111111111', 'admin@mail.com',
        '$2a$10$Xu93DE.ETSXbEGMOJeAT6eUASMcOg9YTzVQ8Rleg2EiwTaP5hHR0.', '0432938573', '963 Willow Way, Capitol City',
        '88097', 'Admin', 'Oneal', 'ROLE_ADMIN', TRUE, '2025-05-16 13:13:13');

INSERT INTO orders (id, order_number, user_id, total_order_price,
                    ordered_date, delivery_date,
                    order_status, shipping_address, payment_method, delivery_postcode)
VALUES
    (99,  'ORD-1001', '11111111-1111-1111-1111-111111111111', 350000,  '2025-05-21', NULL, 'RECEIVED',  '123 Elm Street', 'PAYPAL', 1120),
    (100, 'ORD-1002', '11111111-1111-1111-1111-111111111111', 279800,  '2025-05-10', '2025-05-15', 'DELIVERED', '123 Elm Street', 'CREDITCARD', 1120),
    (101, 'ORD-2001', '22222222-2222-2222-2222-222222222222', 399800,  '2025-05-11', NULL, 'RECEIVED', '456 Oak Avenue', 'BANKTRANSFER', 1120),
    (102, 'ORD-3001', '33333333-3333-3333-3333-333333333333', 1200000, '2025-05-19', NULL, 'SHIPPING', '789 Maple Lane', 'PAYPAL', 1120),
    (103, 'ORD-4001', '44444444-4444-4444-4444-444444444444', 5619800, '2025-05-14', NULL, 'RECEIVED', '321 Birch Rd', 'CREDITCARD', 1120),
    (104, 'ORD-5001', '55555555-5555-5555-5555-555555555555', 600000,  '2025-05-27', NULL, 'CANCELED', '654 Cedar Street', 'PAYPAL', 1120),
    (105, 'ORD-6001', '66666666-6666-6666-6666-666666666666', 138900,  '2025-05-23', '2025-05-26', 'DELIVERED', '213 Spruce Blvd', 'PAYPAL', 1120),
    (106, 'ORD-7001', '77777777-7777-7777-7777-777777777777', 237400,  '2025-05-09', NULL, 'SHIPPING', '987 Aspen Way', 'BANKTRANSFER', 1120),
    (107, 'ORD-8001', '88888888-8888-8888-8888-888888888888', 159800,  '2025-05-18', NULL, 'RECEIVED', '147 Redwood Dr', 'PAYPAL', 1120),
    (108, 'ORD-9001', '99999999-9999-9999-9999-999999999999', 197900,  '2025-05-12', '2025-05-17', 'DELIVERED', '852 Pine St', 'CREDITCARD', 1120),
    (109, 'ORD-10001','aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 629900,  '2025-05-28', NULL, 'RECEIVED', '963 Willow Way', 'PAYPAL', 1120),
    (110, 'ORD-11001','bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb', 39900,   '2025-05-29', NULL, 'RECEIVED', '123 Elm Street', 'PAYPAL', 1120),
    (111, 'ORD-11002','22222222-2222-2222-2222-222222222222', 5559900, '2025-05-30', NULL, 'SHIPPING', '456 Oak Avenue', 'CREDITCARD', 1120),
    (112, 'ORD-11003','33333333-3333-3333-3333-333333333333', 199800,  '2025-05-31', NULL, 'RECEIVED', '789 Maple Lane', 'BANKTRANSFER', 1120),
    (113, 'ORD-11004','44444444-4444-4444-4444-444444444444', 439900,  '2025-06-01', NULL, 'SHIPPING', '321 Birch Rd', 'PAYPAL', 1120),
    (114, 'ORD-11005','55555555-5555-5555-5555-555555555555', 279900,  '2025-06-02', NULL, 'RECEIVED', '654 Cedar Street', 'PAYPAL', 1120),
    (115, 'ORD-11006','66666666-6666-6666-6666-666666666666', 1249900, '2025-06-03', NULL, 'SHIPPING', '213 Spruce Blvd', 'CREDITCARD', 1120),
    (116, 'ORD-11007','77777777-7777-7777-7777-777777777777', 199800,  '2025-06-04', NULL, 'RECEIVED', '987 Aspen Way', 'PAYPAL', 1120),
    (117, 'ORD-11008','88888888-8888-8888-8888-888888888888', 237400,  '2025-06-05', NULL, 'SHIPPING', '147 Redwood Dr', 'BANKTRANSFER', 1120),
    (118, 'ORD-11009','99999999-9999-9999-9999-999999999999', 145800,  '2025-06-06', NULL, 'RECEIVED', '852 Pine St', 'PAYPAL', 1120);


INSERT INTO reviews (review_id, product_id, user_id, rating, comment, created_at)
VALUES

-- User 1111 (Order 100 → Product 5)
('r-001', 5, '11111111-1111-1111-1111-111111111111',
 5, 'Beautiful tone and very responsive keys. Exactly what I was looking for.',
 '2025-05-18 14:30:00'),

-- User 6666 (Order 105 → Products 10 & 15)
('r-002', 10, '66666666-6666-6666-6666-666666666666',
 4, 'Great guitar for the price. Comfortable neck and nice sound.',
 '2025-05-28 10:15:00'),

('r-003', 15, '66666666-6666-6666-6666-666666666666',
 5, 'Perfect beginner violin. Easy to play and sounds great.',
 '2025-05-29 09:20:00'),

-- User 9999 (Order 108 → Products 9 & 17)
('r-004', 9, '99999999-9999-9999-9999-999999999999',
 4, 'Solid build quality and very versatile tones.',
 '2025-05-19 16:45:00'),

('r-005', 17, '99999999-9999-9999-9999-999999999999',
 3, 'Good overall, but the setup needed some adjustment.',
 '2025-05-20 11:10:00'),

-- Additional realistic reviews from other users with delivered items
('r-006', 5, '22222222-2222-2222-2222-222222222222',
 4, 'Nice instrument with warm sound. Delivery was smooth.',
 '2025-06-02 13:25:00'),

('r-007', 10, '33333333-3333-3333-3333-333333333333',
 5, 'Excellent quality and very fun to play!',
 '2025-06-04 10:50:00'),

('r-008', 15, '44444444-4444-4444-4444-444444444444',
 2, 'Decent for beginners, but the tone could be better.',
 '2025-06-05 15:30:00'),

('r-009', 9, '55555555-5555-5555-5555-555555555555',
 5, 'Amazing instrument for the price range.',
 '2025-06-06 12:05:00'),

('r-010', 17, '77777777-7777-7777-7777-777777777777',
 1, 'Arrived with minor defects. Customer support helped though.',
 '2025-06-07 17:40:00');


INSERT INTO messages (
    message_id, user_id, name, email, subject, message, created_at, admin_reply, replied_at, status, read_at
)
VALUES
    ('00000000-0000-0000-0000-000000000001', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
     'Maria Lopez', 'maria82@example.com',
     'Shipping Delay',
     'Hi, I have not received my order yet. Can you check?',
     '2025-05-10 10:15:00',
     NULL, NULL, 'OPEN', NULL),

    ('00000000-0000-0000-0000-000000000002', '22222222-2222-2222-2222-222222222222',
     'Jack Roberts', 'jack.r@example.com',
     'Product Question',
     'Is the PrestoTune White-F suitable for beginners?',
     '2025-05-11 14:30:00',
     NULL, NULL, 'OPEN', NULL),

    ('00000000-0000-0000-0000-000000000003', '33333333-3333-3333-3333-333333333333',
     'Li Chen', 'li.chen@example.com',
     NULL,
     'Just wanted to say your shop is amazing. Thank you!',
     '2025-05-12 09:45:00',
     NULL, NULL, 'OPEN', NULL),

    ('00000000-0000-0000-0000-000000000004', '44444444-4444-4444-4444-444444444444',
     'Sophie Campbell', 'sophie.c@example.com',
     'Broken Item',
     'My violin arrived with a broken string. Can it be replaced?',
     '2025-05-13 16:10:00',
     NULL, NULL, 'OPEN', NULL),

    ('00000000-0000-0000-0000-000000000005', '55555555-5555-5555-5555-555555555555',
     'Daniel Klein', 'daniel.k@example.com',
     'Invoice Request',
     'Could you resend my invoice?',
     '2025-05-13 17:55:00',
     NULL, NULL, 'OPEN', NULL),

    ('00000000-0000-0000-0000-000000000006', '66666666-6666-6666-6666-666666666666',
     'Nina Vargas', 'nina.v@example.com',
     'Return Request',
     'I want to return a piano I ordered. What is the process?',
     '2025-05-14 11:05:00',
     NULL, NULL, 'OPEN', NULL),

    ('00000000-0000-0000-0000-000000000007', '77777777-7777-7777-7777-777777777777',
     'Omar Tariq', 'omar.t@example.com',
     NULL,
     'Thank you for the fast and safe delivery!',
     '2025-05-14 13:40:00',
     NULL, NULL, 'OPEN', NULL),

    ('00000000-0000-0000-0000-000000000008', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
     'Peo Oneal', 'user@mail.com',
     'Pickup Option',
     'Can I pick up the product directly from your store?',
     '2025-05-15 08:25:00',
     NULL, NULL, 'OPEN', NULL),

    ('00000000-0000-0000-0000-000000000009', 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
     'Peo Oneal', 'user@mail.com',
     NULL,
     'Thanks for your help earlier! Great customer service.',
     '2025-05-17 14:50:00',
     NULL, NULL, 'OPEN', NULL),

    ('00000000-0000-0000-0000-000000000010', 'bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb',
     'Maria Lopez', 'maria82@example.com',
     'Gift Packaging',
     'Do you offer gift wrapping for piano purchases?',
     '2025-05-18 11:35:00',
     NULL, NULL, 'OPEN', NULL);


INSERT INTO order_items (order_id, product_id, quantity, price) VALUES

-- 99
(99, 1, 1, 350000),

-- 100 (delivered)
(100, 5, 1, 279900),

-- 101
(101, 8, 2, 199900),

-- 102
(102, 2, 1, 1200000),

-- 103
(103, 3, 1, 5559900),
(103, 15, 1, 19900),

-- 104 (canceled)
(104, 4, 2, 300000),

-- 105 (delivered)
(105, 10, 1, 97500),
(105, 15, 1, 19900),

-- 106
(106, 11, 1, 149900),
(106, 8, 1, 87500),

-- 107
(107, 6, 2, 79900),

-- 108 (delivered)
(108, 9, 1, 89900),
(108, 17, 1, 108000),

-- 109
(109, 1, 1, 350000),
(109, 18, 1, 279900),

-- 110
(110, 6, 1, 39900),

-- 111
(111, 3, 1, 5559900),

-- 112
(112, 7, 2, 99900),

-- 113
(113, 4, 1, 300000),
(113, 10, 1, 139900),

-- 114
(114, 5, 1, 279900),

-- 115
(115, 2, 1, 1200000),
(115, 16, 1, 49900),

-- 116
(116, 15, 2, 99900),

-- 117
(117, 11, 1, 149900),
(117, 8, 1, 87500),

-- 118
(118, 18, 1, 79900),
(118, 19, 1, 65900);
