import type { Order, OrderDTO, OrderItem, OrderItemDTO, OrderStatus, PaymentMethod, Product, ProductCategory, StockStatus, User } from "../types/models";

//Maybe will not be needed ? 

export class OrderMapper {
    // Convert frontend Order to OrderDTO for API calls
    public static toOrderDTO(order: Partial<Order>): OrderDTO {
        return {
            customerEmail: order.user?.email || "",
            customerPhoneNumber: order.user?.phone?.toString() || "",
            shippingStateAndDistrict: "", // You need to add this to your UI
            shippingAddress: order.shippingAddress || "",
            totalOrderPrice: order.totalOrderPrice || 0,
            orderItems: order.orderItems?.map(item => ({
                productId: item.product.id.toString(),
                quantity: item.quantity,
                price: item.price
            })) || []
        };
    }

    // Convert API Order to frontend Order type
    public static fromOrderDTO(dto: OrderDTO, orderId?: number): Order {
        const order: Order = {
            id: orderId || 0,
            orderNumber: "", // Will be generated by backend
            user: this.createDefaultUser(dto.customerEmail),
            totalOrderPrice: dto.totalOrderPrice,
            orderItems: dto.orderItems.map((itemDto, index) =>
                this.createOrderItem(itemDto, index)
            ),
            orderedDate: new Date().toISOString().split('T')[0], // Today's date
            deliveryDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000).toISOString().split('T')[0], // 2 weeks from now
            orderStatus: "RECEIVED" as OrderStatus,
            shippingAddress: dto.shippingAddress,
            paymentMethod: "CREDIT_CARD" as PaymentMethod // Default payment method
        };

        // Set the order reference in each order item
        order.orderItems.forEach(item => item.order = order);

        return order;
    }

    private static createDefaultUser(email: string): User {
        return {
            id: "",
            firstname: "",
            lastname: "",
            email: email,
            postcode: 0,
            active: true,
            createdAt: new Date(),
            role: "ROLE_USER"
        };
    }

    private static createOrderItem(dto: OrderItemDTO, index: number): OrderItem {
        // Create a partial product with just the ID
        const product: Product = {
            id: parseInt(dto.productId),
            name: "",
            category: "PIANO" as ProductCategory, // Default category
            description: "",
            price: dto.price,
            shippingCost: 0,
            brand: "",
            stockStatus: "IN_STOCK" as StockStatus,
            shippingTime: 0,
            active: true,
            images: []
        };

        return {
            id: index + 1, // Temporary ID
            order: {} as Order, // Will be set by parent order
            product: product,
            quantity: dto.quantity,
            price: dto.price
        };
    }
}